/**
 * Activity Api Definitions
 * This is a project for definitions of resource service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityResource } from './activityResource';
import { PageResource } from './pageResource';


export interface ActivityList { 
    page?: PageResource;
    activities?: Array<ActivityResource>;
}

