/**
 * Activity Api Definitions
 * This is a project for definitions of resource service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActivityResource { 
    /**
     * The id of activity
     */
    activityId?: string;
    /**
     * The id of an user who perform action
     */
    userId: string;
    /**
     * The time that action performed
     */
    timestamp?: Date;
    /**
     * The type of action
     */
    actionType: string;
    /**
     * The action source IP address
     */
    requestOriginHost?: string;
    /**
     * The detail about an action
     */
    summary: string;
    /**
     * The entity reference
     */
    resourceId: string;
    /**
     * The source service name
     */
    serviceId: string;
}

