/**
 * Activity Api Definitions
 * This is a project for definitions of resource service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiError { 
    /**
     * The field name that cause an error
     */
    violator?: string;
    /**
     * The violation message for the error
     */
    message?: string;
}

